#!/usr/bin/env bash
# Modified based on github.com/onevcat/Swift-CI
# (which was stolen from vapor).

echo "SPM V4 CodeCov Integration";

# Determine OS
UNAME=`uname`;
if [[ $UNAME != "Darwin" ]]; then
    echo "🚫  Unsupported OS: $UNAME, skipping...";
    exit 0;
fi

PROJ_OUTPUT=`swift package generate-xcodeproj`;
PROJ_NAME="${PROJ_OUTPUT/generated: .\//}"
SCHEME_NAME="${PROJ_NAME/.xcodeproj/}-Package"

echo "🚀  Testing: $SCHEME_NAME";

rvm install 2.2.3
gem install xcpretty
WORKING_DIRECTORY=$(PWD) xcodebuild -project $PROJ_NAME -scheme $SCHEME_NAME -configuration Debug -enableCodeCoverage YES test | xcpretty
bash <(curl -s https://codecov.io/bash)

echo "✅  Done";
