#!/bin/sh
echo "🛠  Building..."
swift package clean
if [[ $? != 0 ]]; then
    echo "❌ Failed to clean"
    exit 1
fi
swift build -c release
if [[ $? != 0 ]]; then
    echo "❌ Failed to build"
    exit 1
fi

echo "💼  Installing..."
cp .build/release/Srt2Bilibili-cli /usr/local/bin/s2bkit
s2bkit
