#!/bin/sh
echo "🚀 Downloading..."
rm -rf Srt2BilibiliKit
git clone https://github.com/ApolloZhu/Srt2BilibiliKit.git
if [[ $? != 0 ]]; then
    echo "❌ Failed to download"
    exit 1
fi
cd Srt2BilibiliKit

echo "🛠  Building..."
swift package clean
if [[ $? != 0 ]]; then
    echo "❌ Failed to clean"
    exit 1
fi
swift build -c release
if [[ $? != 0 ]]; then
    echo "❌ Failed to build"
    exit 1
fi

echo "💼  Installing..."
cp .build/release/Srt2Bilibili-cli /usr/local/bin/s2bkit
if [[ $? != 0 ]]; then
    cp .build/release/Srt2Bilibili-cli ../s2bkit
    MODE="LIMITED"
fi
cd ..
rm -rf Srt2BilibiliKit

if [[ $MODE == "LIMITED" ]]; then
    export PATH=$PWD:"${PATH}"
    echo "⚠️  Adding $PWD to your \$PATH is recommended"
    chmod +x s2bkit
fi
s2bkit
if [[ $? != 0 ]]; then
    echo "❌ Failed to execute"
    exit 1
fi
