#!/bin/sh
sudo gem install jazzy
jazzy --author ApolloZhu --author_url https://apollozhu.github.io --github_url https://github.com/ApolloZhu/Srt2BilibiliKit --module Srt2BilibiliKit
if [[ $? != 0 ]]; then 
    echo "Only be jazzy on macOS!";
    exit 0;
fi
